### ISSUE TITLE
Crash on API v21

### ISSUE THREAD

**Issue by Sese-Schneider** [googlesamples/android-EmojiCompat#10]
```EmojiCompat initialization failed
java.lang.RuntimeException: fetchFonts result is not OK. (1)
at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:307)
at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.access$100(FontRequestEmojiCompatConfig.java:164)
at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$1.run(FontRequestEmojiCompatConfig.java:218)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)```

Crashed on emulator.

**Comment by Sese-Schneider** [comment]
Almost same exception occures on different devices of my users:

    Exception java.lang.RuntimeException: fetchFonts result is not OK. (2)
  
  android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata ()
    android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.a ()
    android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$1.run ()
    android.os.Handler.handleCallback (Handler.java:739)
    android.os.Handler.dispatchMessage (Handler.java:95)
    android.os.Looper.loop (Looper.java:135)
    android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by prerak-trivedi** [comment]
It does crash when you try to use it on a `TextView` since `mResult` is null due to failed initialization

**Comment by Sese-Schneider** [comment]
> I dont think that this would happen in real devices.

I got around 10000 real crashes on user devices

**Comment by siyamed** [comment]
Does it crash or log? Can you add some more information here or create a bug (https://source.android.com/source/report-bugs) ?

**Comment by jameswhiteman** [comment]
I was also seeing the fetchFonts result is not OK (1) error. It was an issue with having the certificates array improperly configured. I'd recommend double-checking that they are set up just like in the sample.
